### PR TITLE
Instruction fix

### PR DESCRIPTION
**Pull request by Pzixel**
I tried to follow my own instruction and have found that it's a bit incomplete. So this guy fixes it.

### CODE REVIEW

**Comment by Pzixel** [comment]
I also propose squash these commits. And I have another problem: for some reason it doesn't work on my another PC :) I checked my configuration twice but I see no difference. I have set both environment variables, I added `%OPENCV_DIR%\bin` to the PATH but when I run `cargo test` I just get following error:
```
   Compiling cv v0.1.0 (file:///C:/Users/Alex/Documents/Rust/cv-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 7.21 secs
     Running target\debug\deps\test_features2d-e23864be15c5cd5e.exe
error: test failed, to rerun pass '--test test_features2d'

Process finished with exit code -1073741515 (0xC0000135)
```

without any details.

Any ideas? I also propose to merge this guy when we solve this problem. We probably need add something in this instruction.

**Comment by nebgnahz** [comment]
Squashing these commits is a great idea. Trick that I know is either `rebase` or reset softly, i.e., `git reset --soft "HEAD~n"` and then `git commit --amend`.

I don't know exactly what's going on with the test case. `0xC0000135` on Windows seems to be something related with `.dll`, so the library is not properly configured? Do other tests pass? Try `cargo test -v` and maybe debug with `cargo test -- --nocapture` to see what's going on.

**Comment by Pzixel** [comment]
@nebgnahz yeah, my instruction is actually wrong. Going to fix it now.

**Comment by Pzixel** [comment]
@nebgnahz fixed

**Comment by nebgnahz** [comment]
Ok, I've merged. Thanks.

P.S. I don't think Github does squashing.

Two changes that I am thinking:
1. I would prefer to host the screenshot on Github.
2. I may move the installation to a separate `Installation.md` file to clean the clutter in README.

**Comment by nebgnahz** [comment]
Screenshot host link: [mingw32-make](https://user-images.githubusercontent.com/941519/34654809-836fe56c-f3b5-11e7-87b3-46bb7667bf34.png)

**Comment by Pzixel** [comment]
@nebgnahz 
image

**Comment by nebgnahz** [comment]
Ah, I missed the drop down icon when clicking the `merge` button... Lesson learned today!

And I agree with your argument that a separate `Installation.md` will make it looks complicated (which I think it is, on Windows, sort of).

**Comment by Pzixel** [comment]
@nebgnahz no, it's just because opencv is precompiled for MSVC and you have to compile GNU version yourself. It's not really complicated, it's just detailed. I could just write `cmake all the stuff`, but it's may be not familiar for windows users, most of them are familiar with C# which has as high level depenency model as rust has: package manager and so on. CMAKE is too low level, so I just explained all step in details to make it easy to perform for newcomers too.

**Pull request merged**
