### PR TITLE
Added Wrappers for Sobel and Scharr Image Gradients

### PR DESCRIPTION
**Pull request by geoeo**
Added wrapper calls and an example. 

https://docs.opencv.org/3.0-beta/modules/imgproc/doc/filtering.html

### CODE REVIEW

**Comment by geoeo** [comment]
No clue how to make formatting acceptable for Travis. I installed clang-format and running the hook script. Or do I have to run a specific clang-format command?

**Comment by vadixidav** [comment]
@geoeo You need to make sure clang format is using the configuration file at the root of the repository.

**Comment by geoeo** [comment]
I did. But there seems to be a problem with the new file I added in the example folder. All tests pass, but the diff command fails? Its probably not expecting a new file

**Comment by Pzixel** [comment]
Just look at travis output

```
0.08s$ diff -u <(cat native/*) <(clang-format native/*)
cat: native/cuda: Is a directory
Is a directory
--- /dev/fd/63	2019-03-12 11:24:28.369862853 +0000
+++ /dev/fd/62	2019-03-12 11:24:28.361862846 +0000
@@ -699,7 +699,8 @@
         [first_image, second_image, method]() { return cv::compareHist(*first_image, *second_image, method); });
 }
 
-void cv_sobel(cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType) {
+void cv_sobel(
+    cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType) {
     cv::Sobel(*src, *dst, ddepth, dx, dy, k_size, scale, delta, borderType);
 }
 
@@ -760,14 +761,13 @@
                           cv::Mat* back_project,
                           const float** ranges);
 void cv_compare_hist(cv::Mat* first_image, cv::Mat* second_image, int method, Result<double>* result);
-void cv_sobel(cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType);
+void cv_sobel(
+    cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType);
 void cv_scharr(cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, double scale, double delta, int borderType);
 EmptyResult
 cv_canny(cv::Mat* image, cv::Mat* edges, double threshold1, double threshold2, int aperture_size, bool l2_gradient);
 }
 
-
-
 #endif  // CV_RS_IMGPROC_H
 #include "mat.h"
 
The command "diff -u <(cat native/*) <(clang-format native/*)" exited with 1.
```

**Comment by geoeo** [comment]
@Pzixel Which tells me? Ive never done this before. If you guys want me to do something then just tell me.

**Comment by Pzixel** [comment]
It tells that for example repo contains this code

```
void cv_sobel(cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType) {
    cv::Sobel(*src, *dst, ddepth, dx, dy, k_size, scale, delta, borderType);
}
```

when according to `clang-format` properly formatted code should be
```
void cv_sobel(
    cv::Mat* src, cv::Mat* dst, int ddepth, int dx, int dy, int k_size, double scale, double delta, int borderType) {
    cv::Sobel(*src, *dst, ddepth, dx, dy, k_size, scale, delta, borderType);
}
```

**Comment by geoeo** [comment]
Thanks for your patience. Since I did my first commit without running .sh script the tracking got messed up.

**Comment by Pzixel** [comment]
Great work!

**Pull request merged**
