### PR TITLE
Feature/general repo improvement

### PR DESCRIPTION
**Pull request by Pzixel**
Here are several improvements:
- `.gitattribute` that manages line endings. I used it in multiple projects with different languages, so it's well-tested. git text autodetect simply doesn't work right for most cases. It's very useful when you have contributors from both Windows and *nix world. Otherwise, line endings issues can occur.
- user scripts for simple windows CUDA installation
- better docs

### CODE REVIEW

**Comment by nebgnahz** [comment]
LGTM.

I think you can merge now after I added you as one collaborator. Do you still want me to merge your MR? Or you were just waiting for all checks?

**Comment by Pzixel** [comment]
@nebgnahz I'm creating PR to see that you are agree with changes. I can merge myself since you approve it.

**Comment by Pzixel** [comment]
Ok, I assume your `LGTM` is appove 🙂

**Comment by nebgnahz** [comment]
Yes, `LGTM` is approval. For future PRs, I can do the merge, although I am not sure what would be the best way to merge.

If I do a `merge`, it will be 2 commits: yours and my merge commit. If I do `squash`, it will be mine (I assume?). Seems `rebase` is the best option?

**Comment by Pzixel** [comment]
The best option IMHO is just approve changes somehow, I'm able to press the button myself. I just don't want to merge changes that you can probably dislike for some reason.

**Comment by nebgnahz** [comment]
Ok! `LGTM` it is if I don't have anything to add/comment about the PR.

**Pull request merged**
