### PR TITLE
configure travis

### PR DESCRIPTION
**Pull request by nebgnahz**

### CODE REVIEW

**Comment by Restioson** [comment]
Seems to work. Can be merged? Ps: does this fix the can't find opencv_core.lib (etc) bug?

**Comment by nebgnahz** [comment]
Ah, this has been merged (I directly patched the master branch).

I used to use travis-ci.com so that I can debug the project. But this is a public repository, so I have to use travis-ci.org: the only way to debug is trial and error. Therefore it has 11 commits...

**Comment by Restioson** [comment]
Ouch, unfortunately that's quite relatable though. So, should this be fixing the runtime bug under Windows?

**Comment by Restioson** [comment]
Huh. When you were referring to a bug on Windows, I thought you were referring to `can't find opencv_core.lib` (what I get). I've installed it by downloading the zip file, maybe I will reclone the repo and try again, and if that fails I will use choco

**Comment by nebgnahz** [comment]
I see.  So according to [this SO question](https://stackoverflow.com/questions/34867289/opencv-3-x-only-contains-one-lib-opencv-world-lib), binary installers have a single `opencv_world.lib` file. When I was testing on AppVeyor, I saw `opencv_world320.lib`, so presumably choco installed OpenCV 3.2. In this case, `can't find opencv_core.lib` makes sense, because there is no longer `opencv_core.lib`. But I think if one builds OpenCV from source on Windows, there will be separate libraries including `opencv_core.lib`; and this project will fail in that case.

**Pull request closed without merging**
